version: 2.1

orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.3

executors:
  test-executor:
    docker:
      - image: cimg/node:14.17-browsers
    resource_class: large

commands:
  install_dependencies:
    description: "Install dependencies"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn

  run_tests:
    description: "Run Playwright tests in parallel"
    parameters:
      parallelism:
        type: integer
        default: 4
    steps:
      - run:
          name: Run Playwright Tests
          command: npx playwright test --project=chromium --workers << parameters.parallelism >> 

jobs:
  test_all_tags:
    executor: test-executor
    parallelism: 4  # Adjust this to change the number of parallel instances
    steps:
      - install_dependencies
      - run_tests:
          parallelism: << parameters.parallelism >>

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_all_tags:
          parallelism: 4  # This number should match the executor's parallelism for consistent sharding

