version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  playwright-tests:
    playwright-cd-tests:
    machine: true
    resource_class: << parameters.resource >>
    parallelism: << parameters.parallels >>
    working_directory: ~/project
    parameters:
      browser::
        type: string
        default: 'chromium'
      baseURL:
        type: string
      resource:
        type: string
      smokeOrRegression:
        type: enum
        enum: ['testTag1', 'testTag2']
      additionalEnvs:
        type: string
        default: 'workers=1'
      parallels:
        type: integer
        default: 1
    steps:
      - run:
          no_output_timeout: 30m
          name: Install checkout tools and test tools
          command: |
            rm -rf samplepw
            sudo rm -f /etc/apt/sources.list.d/nodesource.list
            # Failing on file size when downloading source for node 16
            sudo apt update
            sudo apt install -y ca-certificates gnupg2
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1655A0AB68576280
            sudo apt install --no-install-recommends -y git openssh-client
            curl -sL https://deb.nodesource.com/setup_18.x | sudo bash -
            sudo chmod a+r "/usr/share/keyrings/nodesource.gpg"
            sudo apt-get install -y nodejs
            sudo npm install -g yarn
            sudo rm -rf /var/lib/apt/lists/*
            curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
            git clone --depth=1 https://github.com/adilimroz/samplepw.git --single-branch --branch=master
            ls
            sudo chmod -R 0777 samplepw
            cd samplepw/playwright
            ls
      - run:
          name: Clean old test results
          command: |
            if [ -d "./samplepw/playwright/test-results" ]; then rm -rfv ./samplepw/playwright/test-results; fi
      - run:
          name: Install dependencies
          command: |
            cd samplepw/playwright
            yarn
            npx playwright install --with-deps
      - run:
          name: Run tests in << parameters.browser >>
          command: |
            cd samplepw/playwright
            SHARD="2"; << parameters.additionalEnvs >> baseURL=<< parameters.baseURL >> npx playwright test ./tests/*/*.spec.ts --project << parameters.browser >> -g "@<< parameters.smokeOrRegression >>" --shard=${SHARD}/${CIRCLE_NODE_TOTAL} || true
      - store_test_results:
          path: ./samplepw/playwright/test-results
      - store_artifacts:
          path: ./samplepw/playwright/test-results
          event: fail
      - persist_to_workspace:
          root: ~/project
          when: always
          paths:
            - ./samplepw/playwright/test-results/*.xml
            - ./samplepw/playwright/test-results/**/*.webm
